################################################################################
#                  _             
#  ___ _ __   __ _| | _____  ___ 
# / __| '_ \ / _` | |/ / _ \/ __|
# \__ \ | | | (_| |   <  __/\__ \
# |___/_| |_|\__,_|_|\_\___||___/
#                               
# Example configuration
#
################################################################################

################################################################################
#
# General settings
#
################################################################################

# analysis name and version
name: 'test pipeline'
version: '1.0'

# output directory
output_dir: 'output'

# random seed
random_seed: 1

# output verbosity
verbose: true

# quality control related options
quality_control:
  allow_mismatched_indices: false

################################################################################
#
# Datasets
#
################################################################################
datasets:
  - 'example/yml/rnaseq.yml'
  - 'example/yml/cnv.yml'
  - 'example/yml/variants.yml'
  - 'example/yml/drug_screen.yml'

################################################################################
#
# Datasets
#
################################################################################
training_sets:
    features:
      - 'rnaseq_final'
      - 'rnaseq_go_terms_sum_final'
      - 'cnv_final'
      - 'variants_final'
    response: 'ac50_final'

################################################################################
#
# Data integration
#
################################################################################
#data_integration:
#  - type: 'correlation'
#    datasets:
#        - 'rnaseq_sample_pca_cormat'
#        - 'ac50_sample_pca_cormat'
#    method: 'pearson'

