language: python
matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew install python3
      install:
        - python3 -m pip install --user .
      before_script:
        - python3 -m pip install --user --upgrade pytest
      script: python3 -m pytest
before_script:
  - pip install --upgrade pytest
install:
  - pip install .
script: py.test
