################################################################################
#                  _             
#  ___ _ __   __ _| | _____  ___ 
# / __| '_ \ / _` | |/ / _ \/ __|
# \__ \ | | | (_| |   <  __/\__ \
# |___/_| |_|\__,_|_|\_\___||___/
#                               
# Data integration and machine learning pipeline built on Snakemake
#
# https://github.com/khughitt/snakes
#
################################################################################
import yaml

#
#  {{ config['name'] }} {{ config['version'] }}
#

# load sample and response metadata
sample_metadata   = yaml.load(open('{{ config['metadata']['samples'] }}'))
response_metadata = yaml.load(open('{{ config['metadata']['response'] }}'))

{% for key, feature in features.items() %}
{% include 'data/' + feature['name'] + '.snakefile' %}
{% endfor %}

{#
# vim: ft=python
#}
