################################################################################
#                  _       
#  ___ _ __   __ _| | _____  ___ 
# / __| '_ \ / _` | |/ / _ \/ __|
# \__ \ | | | (_| |   <  __/\__ \
# |___/_| |_|\__,_|_|\_\___||___/
#                 
# Data integration and machine learning pipeline built on Snakemake
#
# https://github.com/khughitt/snakes
#
{% set title_underline = '-' * (config['name'] | length + config['version'] | length + 1) %}
#  {{ config['name'] }} {{ config['version'] }}
#  {{ title_underline }}
#
#  Config : {{ config['config_file'] }}
#  Date   : {{ date_str }}
#
#  datasets:
{% for dat_name, dataset in config['datasets'].items() %}
#  - {{ dat_name }}: {{ dataset['path'] }}
{% endfor %}
#
{% set output_dir = '/'.join([config['output_dir'] | expanduser, config['version']]) %}
#  Output dir: {{ output_dir }} 
#
################################################################################
import glob
import operator
import os
import yaml
import numpy as np
import pandas as pd
from snakes import clustering, filters, gene_sets 

# create output directory, if needed
output_dir = '{{ output_dir }}' 

{#############################################################################################}
{#                                                                                           #}
{# Global variables                                                                          #}
{#                                                                                           #}
{#############################################################################################}
{# list used to keep track of terminal datasets produced for each data source #}
{% set terminal_datasets = [] -%}

{# list used to keep track of simple rules that should not be run on a compute cluster #}
{% set local_rules = [] -%}

{#############################################################################################}
{#                                                                                           #}
{# Default target                                                                            #}
{#                                                                                           #}
{#############################################################################################}
rule all:
    input: "{{ output_dir }}/finished"

{#############################################################################################}
{#                                                                                           #}
{# Datasets
{#                                                                                           #}
{#############################################################################################}
{% for dat_name, dataset in config['datasets'].items() %}
{% include 'data/' + dataset['data_source'] + '.snakefile' %}
{% endfor %}

{#############################################################################################}
{#                                                                                           #}
{# Default target
{#                                                                                           #}
{#############################################################################################}
rule process_data_sources:
    input: expand("{{ output_dir }}/data/{processed_datasets}", processed_datasets={{ terminal_datasets }})
    output: touch("{{ output_dir }}/finished")

{#############################################################################################}
{#                                                                                           #}
{# Other settings                                                                            #}
{#                                                                                           #}
{#############################################################################################}
{% set localrules_str = ', '.join(local_rules) %}
localrules: {{ localrules_str }}

{# vim: set softtabstop=2 shiftwidth=2 tabstop=2 filetype=snakemake: #}
# vim: set filetype=snakemake:
