################################################################################
#                  _             
#  ___ _ __   __ _| | _____  ___ 
# / __| '_ \ / _` | |/ / _ \/ __|
# \__ \ | | | (_| |   <  __/\__ \
# |___/_| |_|\__,_|_|\_\___||___/
#                               
# Example Configuration
#
################################################################################

################################################################################
#
# General settings
#
################################################################################

# analysis name and version
name: 'example pipeline'
version: '1.0'

# output directory
output_dir: 'output'

# random seed
random_seed: 1

################################################################################
#
# Data sources
#
################################################################################
datasets:
  features:
    - 'settings/features/rnaseq.yml'
    - 'settings/features/cnv.yml'
  response:
    - 'settings/response/drug_screen.yml'

metadata:
  samples: 'tests/data/sample_metadata.csv'
  response: 'tests/data/drug_metadata.csv'
 

################################################################################
#
# Samples
#
################################################################################
exclude_samples: 
  - 'KMS21BM_JCRB'
  - 'Karpas417_ECACC'
  - 'SKMM1_PLB'

################################################################################
#
# Global filters
#
################################################################################
filter:
  exclude_columns:
    type: 'exclude_columns'
    column_id: 'sample_id'
    columns_to_exclude:
      - 'KMS21BM_JCRB'
      - 'Karpas417_ECACC'
      - 'SKMM1_PLB'
  zero_variance:
    type: 'row_variances'
    cutoff_value: 0

################################################################################
#
# Aggregation settings
#
################################################################################
clustering:
  hclust:
    num_clusters: 100
    fxns: ['median', 'sum', 'max', 'var']
gene_sets:
  msigdb:
    gmts:
      - '/path/to/h.v6.1.entrez.gmt'
      - '/path/to/c2.v6.1.entrez.gmt'
      - '/path/to/c6.v6.1.entrez.gmt'
      - '/path/to/c7.v6.1.entrez.gmt'
    fxns: ['median', 'sum', 'max', 'var']

################################################################################
#
# Feature selection
#
################################################################################
feature_selection:
  enabled: true
  balance_data: false
  remove_correlated_features: true
  max_feature_cor: 0.75
  num_iterations: 15000
  features_per_subsample: 2000
  random_forest_ntree: 10000
  random_forest_mtry: 4

################################################################################
#
# Training set filters
#
################################################################################
training_set_filters:
  min_nonzero: 4

################################################################################
#
# Machine learning
#
################################################################################
machine_learning:
  method: 'random_forest'

################################################################################
#
# Software
#
################################################################################


