################################################################################
#                  _             
#  ___ _ __   __ _| | _____  ___ 
# / __| '_ \ / _` | |/ / _ \/ __|
# \__ \ | | | (_| |   <  __/\__ \
# |___/_| |_|\__,_|_|\_\___||___/
#                               
# Example Configuration
#
################################################################################

################################################################################
#
# General settings
#
################################################################################

# analysis name and version
name: 'example pipeline'
version: '1.0'

################################################################################
#
# Data sources
#
################################################################################
features:
  - settings/features/rnaseq.yml
  - settings/features/cnv.yml
  - settings/features/variants.yml

response:
  - settings/response/drug_screen.yml

metadata:
  samples: extra/example_data/samples.csv
  response: extra/example_data/drugs.csv

################################################################################
#
# Feature selection
#
################################################################################
feature_selection:
  enabled: true
  method: 'random_forest'

################################################################################
#
# Machine learning
#
################################################################################
machine_learning:
  method: 'random_forest'

################################################################################
#
# Software
#
################################################################################

