shared:
  type: 'str'
filter_exclude_columns:
  columns_to_exclude: 'list'
filter_gene_type:
  include_gene_types: 'list'
filter_include_columns:
  columns_to_include: 'list'
filter_numeric_cutoff:
  group: 'str'
  field: 'str'
  stat: 'str'
filter_row_field_above:
  field: 'str'
filter_row_max_group_stat:
  group: 'str'
  field: 'str'
  stat: 'str'
filter_row_min_group_stat:
  group: 'str'
  field: 'str'
  stat: 'str'
